# Generated by Django 3.1.3 on 2023-04-29 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='factura',
            fields=[
                ('numerofactura', models.CharField(max_length=10000, primary_key=True, serialize=False)),
                ('cliente', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('valor', models.PositiveBigIntegerField()),
            ],
        ),
    ]

